version: '3.5'

services:
  redis_proxy:
    container_name: 'redis_proxy'
    build: .
    depends_on:
      - redis
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      local:
        aliases:
          - "${APP_HOST}"


  redis:
    container_name: 'redis'
    image: redis:latest
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: on-failure
    networks:
      - local
    command: "redis-server --maxclients ${REDIS_MAX_CLIENTS}"

  nginx:
    container_name: 'nginx'
    image: nginx:latest
    depends_on:
      - redis_proxy
    env_file:
      - .env
    ports:
      - "${PROXY_PORT}:${PROXY_PORT}"
    volumes:
      - ./nginx/proxy.tmpl:/etc/nginx/conf.d/proxy.tmpl
      # - ./nginx/nginx.tmpl:/etc/nginx/nginx.tmpl
    restart: on-failure
    networks:
      - local
    command: /bin/sh -c "envsubst < /etc/nginx/conf.d/proxy.tmpl > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

networks:
  local:
